### ISSUE TITLE
Fix pipeline - it failed for no reason build #5

### ISSUE THREAD

**Issue by buep** [Praqma/git-phlow#108]
I would say the concourse pipeline failed without any reason, I just pushed a markdown file. There are no errors stated in the console, still the build failed.

https://concourse.bosh.praqma.cloud/teams/main/pipelines/git-phlow/jobs/integration-test/builds/5

And you might wan't clean up my mess after I pushed manually using a PR: https://github.com/Praqma/git-phlow/pull/107

**Comment by buep** [comment]
See #106

**Comment by buep** [comment]
Goes for #109 and PR #110 as well now

**Comment by buep** [comment]
Explanation ...
```
go builds before tests and i the top this is shown `cmd/issues.go:17: undefined: ui in ui.Format
cmd/park.go:18: undefined: ui in ui.Format
cmd/web.go:22: undefined: ui in ui.Format`
```
- that is what makes it fail!

We should save stacktrace, and further the above message doesn't say fail or warning or what-ever

**Comment by groenborg** [comment]
@buep So reason it failed was due to a new configuration. Before we ran tests in the old repository not the one with the merged branch so it did not catch an existing error that have been added recently. To fix it we just have to apply that fix
