### ISSUE TITLE
git phlow deliver --local is misleadning

### ISSUE THREAD

**Issue by buep** [Praqma/git-phlow#122]
since it pushes something - so where do the local comes?

What was the reasoning about calling `--local`  for "local" ?

I would rather say `--force` ... as it skips the verification process.

**Comment by groenborg** [comment]
The `local` flag indicates that it is happening on your computer and not on a server. This command is also available as an `agent` subcommand. It is actually possible to run your tests as a part of the `deliver --local` command. The force indicates that we skip validation, but we do not, it is just optional.

**Comment by groenborg** [comment]
I will close this issue since this has been a debate for quite some time now. The local deliver command will be replaced as an agent sub command in the future

**Comment by buep** [comment]
Fine, as long and the local word disappears when a push is included.
