### ISSUE TITLE
Running wrapup without git credentials configures results in an incorrect error message

### ISSUE THREAD

**Issue by praqma-thi** [Praqma/git-phlow#132]
*Scenario*
 - You are missing the your `user.name` and `user.config` configuration (_.gitconfig_)
 - You _have_ staged changes in your repository.
 - You call `git phlow wrapup`

*Result*
You receive the error message: `Nothing to commit.`
Behind the scenes, git actually informs you your `user.name` and `user.email` aren't set.
If it then fails to auto-detect these properties, it will exit with an error, e.g. `fatal: unable to auto-detect email address (got 'adamhenriques@Adams-MacBook.(none)')`

*Problem*
The error git-phlow shows does not accurately represent the actual problem you are facing.

*Solution*
Report the actual error you run into, rather than assuming the user doesn't have anything to commit.

**Comment by groenborg** [comment]
Adding issue to backlog. Thank you for the contribution
