### ISSUE TITLE
Plan Jira workflow 

### ISSUE THREAD

**Issue by groenborg** [Praqma/git-phlow#142]
The workflow for Jira needs to coordinated

**Comment by buep** [comment]
We have an agreement with our customer about we propose it. So this means the explained workflow in the SoW can be used.

Let's spend some time today on this, making sure to draw up the workflow.

**Comment by groenborg** [comment]
From the meeting @buep And I had, we are gonna use the proposed standard workflow based on this diagram: https://confluence.atlassian.com/adminjiraserver072/working-with-workflows-828787890.html The workflow need to be documented towards how it works on GitHub. In GitHub we label, and in Jira we transition to a new status.

**Comment by groenborg** [comment]
Based on the comment above I will close the issue and let it be the entrypoint for issues regarding the Jira implementation
