### ISSUE TITLE
Add Chocolatey package

### ISSUE THREAD

**Issue by groenborg** [Praqma/git-phlow#143]
Add the windows binary as a chocolatey package. Add the buildstep for the package in concourse.

**Comment by groenborg** [comment]
Link to the official chocolatey package https://chocolatey.org

**Comment by kryptag** [comment]
To get git-phlow on Chocolatey we need to add a .nuspec file which is an XML file that describes the project.

Write a small script that takes the new release - Build it - Test it - Push it to Chocolatey.

**Comment by kryptag** [comment]
This issue spawned #156 & #157
