### ISSUE TITLE
Add .nuspec file to become compliant with Chocolatey

### ISSUE THREAD

**Issue by kryptag** [Praqma/git-phlow#156]
Ressources for .nuspec documentation: https://docs.microsoft.com/da-dk/nuget/schema/nuspec

**Comment by kryptag** [comment]
We have chosen to go with Scoop for now, Because it fits our purpose more than doing Chocolatey. We might do a Chocolatey release in the future, but for now this issue will be in the backlog.

**Comment by groenborg** [comment]
fixed in #231
