### ISSUE TITLE
Shell script that can publish the new Release to Chocolatey

### ISSUE THREAD

**Issue by kryptag** [Praqma/git-phlow#157]
there are 3 steps that need to be met before we can publish on Chocolatey

1. we need to build the new git-Phlow release 
2. we need to test that the package was build correct and that everything is complaint with the Choco guidelines
3. we need to publish the package if step 2 was successful

**Comment by kryptag** [comment]
We have chosen to go with Scoop for now, Because it fits our purpose more than doing Chocolatey. We might do a Chocolatey release in the future, but for now this issue will be in the backlog.

**Comment by groenborg** [comment]
fixed in #231
