### ISSUE TITLE
--versions does not descibe anything if it is a developer build

### ISSUE THREAD

**Issue by bicschneider** [Praqma/git-phlow#161]
```
Claus@cls-ux301la  /d/customers/praqma/code-utils/bitbucket (master)
$ /d/customers/praqma/git-phlow/src/github.com/praqma/git-phlow/git-phlow.exe --version
false
phlow specification
sha             :
version         :
date            :
```
It should retrieve the information from:
`git describe --tags --dirty`
+ `date/time` and `username`

**Comment by groenborg** [comment]
That is because you as a developer have to add the necessary flags.. Look in `ci/build/linux.sh` if you run the go build command locally, you get what you want.,
