### ISSUE TITLE
workon for jira grooming

### ISSUE THREAD

**Issue by groenborg** [Praqma/git-phlow#163]
Aa a user I want the program to move the issue to next state when I work on it, so other people can see that It is in progress. 

- [x] Need to support a target configuration
workon is hardcoded to use the default configuration, that needs to be changed so it can receive a ini block name.

- [x] Jira needs to call next state on an issue so it will be moved to WIP  
Next state needs to be abstracted away so it also works with the GitHub set label

To achieve the desired functionality we need to implement 4 rest calls for The Jira API
- get Issue (to get the current state)
- get transitions (to see if In Progress is available)
- set transition (to set the transition to In progress)
- set assignee (to set the assignee of the issue now in progress)

The call order: 
`get issue ` -> `get transition` -> `set transition` -> `set assignee` ---> git work from here
If the first step fails the branch will not be created.. Otherwise it will

**Comment by groenborg** [comment]
A transition can be located by calling http://jira.com/rest/api/2/issue/TIS-41

**Comment by groenborg** [comment]
### Considerations for further improvement

Right now we are only compliant with the standard lira workflow as mentioned in slack by @buep, which can be seen here https://confluence.atlassian.com/adminjiraserver072/working-with-workflows-828787890.html 

From our research we have found that we have to do name comparison on the states and transitions because the ID's are not statically defined within Jira. This limits the workflow and will force users to Have `Open` as the initial state and `In Progress` as the next state.       

We can in a future release make this configurable by creating mappings in our config files so the names are changeable.

**Comment by buep** [comment]
Yes. Open as first state and in progress as next state seems right. Isn't that also what I wrote in my SoW?

**Comment by buep** [comment]
Initial state doesn't mattet, do it? I'm expecting git phlow to just transition the issue to next state when doing work on. Wouldn't that work?

**Comment by groenborg** [comment]
@buep from the API documentation the Post request `Do transition` need a transition ID before it will move the issue, since there can be multiple transitions. https://docs.atlassian.com/jira/REST/server/#api/2/issue-doTransition If you have found documentation otherwise that would be helpful

**Comment by buep** [comment]
I found documentation enough somewhere to conclude that one or several call could give us a next state transition. I failed to reference them if they are not in the SoW.
Please make an issue in that case on two hours for this research with worklog I can read before we conclude.

**Comment by groenborg** [comment]
We have look through the official documentation, and it clearly states that any attempt to move the transition without a transition id will result in an `error 400`. If we however do not care about the Initial state we can leave that out, but we can not transition without an ID

**Comment by buep** [comment]
From slack discussion: 

simon [Today at 13:04] 
in #git-phlow
@bue.petersen Do workon on Jira need to set assignee as well


5 replies
bue.petersen [1 hour ago] 
If we do that on github also. Then yes


simon
[1 hour ago] 
ok.. please read the workon issue on git-phlow about jira support.. There are some consideration @bue.petersen


bue.petersen
[1 hour ago] 
I answered... Please read the SoW and conclude if we deviated or not


simon
[1 hour ago] 
@bue.petersen Technically speaking it says nothing about an assignee.. however that may be expected since we have promoted that behaviour


bue.petersen
[1 hour ago] 
Expected to work like with github as close as possible

**Comment by buep** [comment]
@groenborg - your call order is wrong... please consult the SoW which says:

> When the git-phlow workon command are not able to transition the Jira issue to ‘IN PROGRESS’ status it will report a warning but complete the git changes like creating the branch.

**Comment by buep** [comment]
I'm making this a briefing... it to unclear now, good thing we didn't put it in progress.
