### ISSUE TITLE
Chocolatey vs Scoop

### ISSUE THREAD

**Issue by groenborg** [Praqma/git-phlow#173]
Chocolatey is a package manager for windows software which can be used too install various packages. For a package to be installed it has to be approved by chocolatey and thus actually provides a hindrance for quick releases, however the tool seems quite popular. 
Scoop is an alternative we consider instead, and after a few test we can see that it might be a better option. Scoop is specifically made for command line tools and custom buckets (taps in brew) can be added with you own set of tools. Scoop does not support installation of versions however, but it is very easy to use and install. Chocolatey can come back into scope at a later time if necessary. 

It is unsatisfying to install the git-phlow.exe from the GitHub release zip file, and to help our customers an easy package manger will provide the installation of the tool. 
With this in mind, we will go with Scoop and create the installation setup.

**Comment by groenborg** [comment]
We chose scoop and that will act as our future package manage until requirements change. This issue will be closed

**Comment by RandomSort** [comment]
I think that Kamstrup still expects chocolatey packages, or am I completely off?

**Comment by buep** [comment]
No - I promised them a chocolatey package before we wrap-up - until then we continue with scoop because they already can install that and we want their features to work before the chocolatey package

**Comment by buep** [comment]
Closing see #231
