### ISSUE TITLE
Web for Jira

### ISSUE THREAD

**Issue by groenborg** [Praqma/git-phlow#184]
To open an issue on the Jira website. If no issue ID is available, the standard action is to open the list of issues!

### Changes
- issue can no longer be parsed as an int
- Url to internal Jira must be available in ProjectSettings
  - There must be an Issue URL - if we use different services for issues and repo
  - There must be a repo URL
- Default browser on windows
Can we launch the browser on windows like we do on linux? 

### behaviour
When issue can be derived from context, we navigate to the repository site and NOT the issue site. This behaviour should be the same on GitHub

**Comment by lakruzz** [comment]
Can we derive the full URL just from knowing the ID?


Example:

Based on a Jira issue like this: https://issues.jenkins-ci.org/projects/JENKINS/issues/JENKINS-46173 . we should probably create a branch name like this would generate a branch name like:

JENKINS-46173-support_for_owasp_dependency-check_plugin

Do we know, if we can derive the issue url back from this?

It appears the asking the issue on the API _doesn't_ reveal the external link 

https://issues.jenkins-ci.org/rest/api/latest/issue/JENKINS-46173

Do we have any possible way of _knowing_ this - or do we need to _guess_

**Comment by lakruzz** [comment]
maybe we need help from Jira experts like @ThaKangBaby @alpap @praqmaTim ...or sombody else, who is Atlassian certified expert!

**Comment by JKrag** [comment]
I am pretty sure that the external "browser "  link to the issue is returned in the json data when you query the issue. As I recall, I have used this in PAC for putting links in release notes. I can check tomorrow.

**Comment by groenborg** [comment]
Jira keeps the state of moved and renamed issues. So when an issue with key WEB-35 is moved to a new project and gets e.g. APR-21, The API keeps the state and finds the right issue also on the website. So we do not need to use the id

**Comment by groenborg** [comment]
to go to the website of the issue: 

website.com/browse/KEY

**Comment by praqmaTim** [comment]
@lakruzz - I have given my feedback to Simon and he can move forward.

**Comment by JKrag** [comment]
https://community.atlassian.com/t5/Answers-Developer-Questions/Get-url-of-Issue-via-REST-API/qaq-p/498109
also claims that "constructing" the url is the correct approach.

**Comment by lakruzz** [comment]
@groenborg 

>to go to the website of the issue:
>
>website.com/browse/KEY

Seems to _not_ work.

In the example

 https://issues.jenkins-ci.org/projects/JENKINS/issues/JENKINS-46173

I can query the id from from the rest API

https://issues.jenkins-ci.org/rest/api/latest/issue/JENKINS-46173

It says "184413"

So 

https://issues.jenkins-ci.org/browse/184413

...should then be valid?

..it's not!

**Comment by lakruzz** [comment]
SOOOORRY @groenborg: mistook _KEY_ for _ID_

I read the link @JKrag provided 👍  and it's the `ISSUEKEY` not the `ISSUEID` that's needed.

SO

https://issues.jenkins-ci.org/browse/JENKINS-46173

Voíla!

**Comment by groenborg** [comment]
fixed in #247
