### ISSUE TITLE
Issues for Jira

### ISSUE THREAD

**Issue by groenborg** [Praqma/git-phlow#186]
As a developer I would like to view my issues on Jira in my terminal. 
Jiras 'search' api can get all the issues a user has access to, with basic authorization.

To finish this feature, we need to implement a web request for the issues, and a way to print them in the terminal.

**Comment by lakruzz** [comment]
related to #184 

It seems like we need two URLs configured - _always!_

* One for the repo
* On for the issues

When we are using GitHub for both repo and issues it's easy:

`repo:https://github.com/praqma/git-phlow`
`issues:https://github.com/praqma/git-phlow/issues`

**Comment by groenborg** [comment]
A query on the issue with an empty search param will bring back all issues you have permissions to see

**Comment by groenborg** [comment]
Subtasks are identical the same as normal issues, so they will be listed just like normal issues
