### ISSUE TITLE
Wrapup for Jira

### ISSUE THREAD

**Issue by groenborg** [Praqma/git-phlow#188]
When issues are delivered with a #close in the commit message, the issues should be closed automatically, as it does in GitHub. 

Jira supports smart commit, so this feature is already implemented, it just needs to be tested to see if it works, and if not how the smart commits are enabled.

**Comment by lakruzz** [comment]
We need JIRA to be able to do something similar to this: https://help.github.com/articles/closing-issues-using-keywords/

If it doesn't exist, we will have to implement it.

**Comment by lakruzz** [comment]
...seems like there is _something_  here:

https://confluence.atlassian.com/bitbucket/resolve-issues-automatically-when-users-push-code-221451126.html

**Comment by lakruzz** [comment]
...ooops seems to be relevant for bitbucket cloud - we need this to work in an on-premises setup too.

**Comment by lakruzz** [comment]
@hoeghh @praqmaTim ?

**Comment by praqmaTim** [comment]
Smart commits should work on server instances also.

https://confluence.atlassian.com/bitbucketserver/using-smart-commits-in-bitbucket-server-802599018.html

**Comment by groenborg** [comment]
Smart commit are only support is you use the Suite which means BitBucket and Jira. That does not present a problem however since it matches the SoW.

**Comment by groenborg** [comment]
This feature is complete separated from everything. So nothing needs to be changed unless line endings are a problem, which is an easy fix. I will therefore resize the issue

**Comment by buep** [comment]
If possible within the new size - add a test for the line endings if we have the test mechanisms for it - else leave it for the test strategy, but mention it on our combinatorial drawing.

**Comment by groenborg** [comment]
@buep I do not think it is necessary, because we found a way to let go decide the line endings based on the OS if I remember correctly, so this is more about figuring out if we also added that feature to this command. However I think you are right and we need a test if that is not the case

**Comment by buep** [comment]
ok

**Comment by groenborg** [comment]
Wrapup was testing in issue #233 and no errors was found regarding features for the new release. I will close this issue
