### ISSUE TITLE
Follow up on windows support

### ISSUE THREAD

**Issue by groenborg** [Praqma/git-phlow#201]
Phlow have been released on windows and is undergoing internal beta testing by our developers. Follow up on their testing and findings to see how stable git-phlow is on windows. 

@MadsNielsen and @MichaelMadsen are the two primary testers on this.

**Comment by buep** [comment]
@MadsNielsen @MichaelMadsen - ping, do it work for you? Any feedback?

What versions are you running?

**Comment by buep** [comment]
@MichaelMadsen didn't test it... haven't heard anything from Mads. Closing.
