### ISSUE TITLE
Don't finished the deliver - when it's not succesful

### ISSUE THREAD

**Issue by lakruzz** [Praqma/git-phlow#207]
![image](https://user-images.githubusercontent.com/155492/29556835-5df274c6-8727-11e7-88af-796f8a39b27b.png)

...happened to @anetacamo when password was mistyped.

This should _not_ have an effect on the workon state - since she didn't successfully deliver - yet

**Comment by groenborg** [comment]
The mistyped password was for the https git url., When changing the remote to a git url using ssh it uses the key in stead, which seems to work. Then she does a workon and a deliver. I cannot see the issue.
