### ISSUE TITLE
Please - continue (new .phlow file)

### ISSUE THREAD

**Issue by JasmineCrozier** [Praqma/git-phlow#208]
![image](https://user-images.githubusercontent.com/24294535/29663892-90322402-88cd-11e7-8af3-48641a09a393.png)

When no `.phlow` file exist - we create it.

Why do we still fail then? - shouldn't we just do what the user asks us to do - instead of asking the user to do it again?

**Comment by lakruzz** [comment]
See #209

**Comment by groenborg** [comment]
This will be addressed in #209
