### ISSUE TITLE
User scenarios .phlow

### ISSUE THREAD

**Issue by lakruzz** [Praqma/git-phlow#209]
Here's how I would like to see the desired behaviour of our `.phlow` files

- [x] must be a valid git config file

Currently we're using underscores in some of our key names - that is not compliant 

- [x] all properties that can be set from the `.phlow` file must have program defined defaults

- [x] all program defaults should work against GitHub and GitHub issues

- [x] all defaults must be configurable on machine level (`system`) user level (`global`) and repository level (`.phlow` in repo root)

Currently we're not git config file compliant

- [ ] All phlow settings shall be part of the git config query system 

Eample

```shell
git config --get phlow.remote
```
Currently the `.phlow` file in the repo is queried directly by  git-phlow program.

The `.phlow` should be renamed to `.gitconfig` in order to  adapt to conventions - and can be included in the standard git query by the following command (assuming it's made compliant prior to this step):

```shell
git config --local include.path ../.gitconfig
```
This is results in the following include clause in the repos `/.git/config` file:

```ini
[include]
	path = ../.gitconfig
```

- [ ] the phlow shall be able to run (using program defaults) even if none of the three configuration levels are defined

Example: only if the `git config...` query in the example above returns a non-zero error coder shall program defaults be used.

Currently .phlow is required in the repo

- [ ] the local .phlow file shall not be created automatically.

Currently it's created if it doesn't exist

**Comment by lakruzz** [comment]
**Solution**

It appears that including the local (repo) level is what seems to be causing the challenge here.

But I think I found a viable solution. 

In the following examples it's assumed that the content of `.phlow` is made compliant so the current settings :

```ini
[default]
  remote                 = origin
  service                = github
  integration_branch     = master
  issue_url              = https://api.github.com
  delivery_branch_prefix = ready
```
are changed to 

```ini
[phlow]
  remote                 = origin
  service                = github
  integration-branch     = master
  issue-url              = https://api.github.com
  delivery-branch-prefix = ready
```

1. The section `default` is changed to `phlow``
2. All underscores `_` are changed to dashes `-``

Actually since these are all default values they could all be removed.

**Example**
Changing a setting on a global scope.

This can be done using git config:

![image](https://user-images.githubusercontent.com/155492/29747991-24cbe400-8b0c-11e7-98a3-1e19bc590ed6.png)

The first query fails - be after it's set - it's valid. The information is persisted in the `~/.gitconfig` which now contains

```ini
[phlow]
	...
        ...
	service = bitbucket
```

**Comment by lakruzz** [comment]
**Note on writing to the local `.gitconfig`file**

To ensure that this is stored in a `.gitconfig` file in the root of the repo we must either

1. Change directory to the repo root before execution
2. include the repo root to the path


```shell
cd `git rev-parse --show-toplevel`
git config --file .gitconfig --add phlow.integration-branch gh-pages
```

or

```shell
git config --file `git rev-parse --show-toplevel`.gitconfig --add phlow.integration-branch gh-pages
```

**Comment by groenborg** [comment]
@lakruzz Do we want a config command with git phlow that can bootstrap a new configuration file if the user wants, and a command that enables the user to see a configuration without having to look through .gitconfig files? 

e.g.
#### Bootstrap
```
git phlow config bootstrap
```
creates a new .gitconfig with a default configuration for the user to change


#### Show config
```
git phlow config show jira
```
prints the Jira configuration to the terminal

**Comment by lakruzz** [comment]
@groenborg 

Don't we just want to implement the (_missing_)  git config switch?

```
git config --repo ...
```
