### ISSUE TITLE
Update documentation on how to update with scoop on Windows

### ISSUE THREAD

**Issue by buep** [Praqma/git-phlow#210]
Feedback from user:

> Kan man opgradere via scoop? f.x.:
> ```scoop upgrade git-phlow```
> 
> Det kunne man (med update):
> ```git-phlow --version
> phlow specification
> sha             : aa0b5a9ba306a5d725c0cfd9a09a0dea4aeae844
> version         : 3.0.6
> date            : 21-08-2017
> ```
> 
> måske god idé at tilføje "Upgrading git-phlow" til README.md
>

**Comment by groenborg** [comment]
Yes.. Scoop can be updated. After a `scoop update` which updates the manifests for the CLI's the command `scoop update *` will update all tools with updates. `scoop update git-phlow` should update git phlow

**Comment by groenborg** [comment]
I will also add how to install a pre-release from the AWS bucket
