### ISSUE TITLE
When using Jira it seems like git-phlow try to talk to Github

### ISSUE THREAD

**Issue by buep** [Praqma/git-phlow#212]
See #211 for what user did.

The user also reported a trace of the request, which looks like it tries to connect to Github - if one looks at the payload and their two respectively APIs:

```
POST /authorizations HTTP/1.1
Host: jira.customer.com
User-Agent: Go-http-client/1.1
Content-Length: 99
Authorization: Basic A23Heyas0GAF
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

{"scopes":["public_repo","repo","repo_deployment","repo:status"],"note":"git phlow DK-PRJKEY-AT5698"}
```

## Deliveries

Look for existing test-cases that shows we test both github and jira API's and find the place in the code where we can clearly see the two are separated.
Make a design for test-cases if no test-cases exists.
We will use API mock-up instead of running instances.

**Comment by kryptag** [comment]
This should be fixed by #220
