### ISSUE TITLE
A configuration file is introduced but documentation says nothing

### ISSUE THREAD

**Issue by buep** [Praqma/git-phlow#213]
Please explain location of the files, their content and how to configure them. What is autogenerated, what is not. What can be tweeked.

On any os where are they put. Which are global or project scope?

**Comment by groenborg** [comment]
documentation can be found here: https://github.com/Praqma/git-phlow/tree/master/docs

**Comment by buep** [comment]
I'm missing a link from the repo root README to this piece of documentation. Or if we have git-phlow hosted docs like 2git have then to that one.
Else just to the readme. 

It is a simple fix.

**Comment by groenborg** [comment]
fixed in issue #238
