### ISSUE TITLE
`git phlow workon 1` not working on repo the belongs to an organization

### ISSUE THREAD

**Issue by nielsoledam** [Praqma/git-phlow#222]
### Steps to reproduce

1. Sucessfully install git-phlow via homebrew on Mac.
2. Authenticate github through `git phlow auth`
3. `git phlow workon 1` returns
<img width="733" alt="data-analysis -bash 151x37-1" src="https://user-images.githubusercontent.com/6683253/30005442-0e9852cc-90e3-11e7-862d-0edb7488cf90.png">

Checked that Issue is there using `ghi`:
<img width="387" alt="data-analysis -bash 151x37" src="https://user-images.githubusercontent.com/6683253/30005439-fdbd8fbc-90e2-11e7-97ee-4af8260ce2b2.png">

Also checked that a Personal Access Token exists on Github – which it does:
`git phlow XXXXXXXXXXX.local — public_repo, repo, repo:status, repo_deployment`

It has status "Never used".

**Comment by groenborg** [comment]
Hi @nielsoledam, thanks for your feedback
can you tell me the version of git-phlow you are using. We had an unfortunate change in our authentication which failed to store the created token in you global .gitconfig file, which we are addressing now.

**Comment by nielsoledam** [comment]
version 	: 3.0.6
date 		: 21-08-2017

**Comment by groenborg** [comment]
Hi

We have just released the newest version of git-phlow, which should resolve the issue. The problem you are having is located in a check that is executed before the command. That has now been removed. If you are having anymore problem please submit a new issue.
Thanks for your feedback

**Comment by nielsoledam** [comment]
Thanks, that solved the issue. :-)
