### ISSUE TITLE
Testing strategy for git phlow

### ISSUE THREAD

**Issue by Sharor** [Praqma/git-phlow#229]
This issue stems from #228 and https://github.com/Praqma/Praqmatic-Automated-Changelog/issues/100

Git phlow in its entirety is a command line tool, and as such has its API directly exposed to its users. For any given project, the testing pyramid is a good indicator of where to put testing efforts. 

![image](https://user-images.githubusercontent.com/12966451/30065171-4d010eec-9254-11e7-9847-b4f0e36a49ae.png)

For Git Phlow, this means more concretely that we need to figure out how that fits together with a commandline driven tool. 
The manual testing of the image, is of course exploratory testing which should only ever be done to write more tests in a Praqma scenario. 

Phrasing a testing strategy for golang, and figuring out how to consistently execute on the various underlying OS is relevant. 
A key effort here should also be to evaluate what are "happy paths" that are worth testing on higher levels, as these tests are expensive to maintain and write. 

It's also worth to consider if system tests are relevant for 'ghi' as this is basically the only part returning GUI.

**Comment by buep** [comment]
I'm expecting a commit now soon, since you're supposed to deliver something within time and time is out in 25 minutes :-)

**Comment by buep** [comment]
Or a google document... anything :-)

**Comment by Sharor** [comment]
Lunch is a thing 😛

**Comment by Sharor** [comment]
This has been integrated with master, and is considered closed post discussion.
