### ISSUE TITLE
Add workon cmd

### ISSUE THREAD

**Issue by groenborg** [Praqma/git-phlow#230]
With the reset calls added in Issue #226, we need to add the workon command logic in issue #163 and make it support a target configuration. 

The call order of the Jira API was: `get issue` -> `get transitions` -> `do transition` -> `set assignee` 
The command should only fails if we do not get an issue. That would means that we try to work on an non existent issue which is not allowed. Other wise it should work even if we can't transition the issue. 

The git logic should be the same, and must be abstracted away

**Comment by groenborg** [comment]
I have discovered that a large amount of the code in workon is legacy and is therefore I bigger task than expected. 

What works:
- The rest calls have been implemented
- The workon command does support target configuration
- The command does create a workspace from issues on both `jira` and `github`

What does not work is: 
- set assignee
- set state/label

The code runs and will pass a tollgate test, so I will deliver it. It does however not work as an rc.

I will create a new issue, which will be fixing the assignee and labels/state for both Jira and Github

**Comment by buep** [comment]
> I have discovered that a large amount of the code in workon is legacy and is therefore I bigger task than expected.

What was blocking? And will that be fixed in the next issue? (which is ...?)

**Comment by groenborg** [comment]
Legacy was from the API calls gh.go
https://github.com/Praqma/git-phlow/blob/b8ad85e093379c05485661f538a5b06a398f8365/plugins/gh.go#L18-L57

https://github.com/Praqma/git-phlow/blob/b8ad85e093379c05485661f538a5b06a398f8365/plugins/gh.go#L134-L216

Further more, there is no interface segregation or dependency injection in either of the places I need to edit, so every function used from other classes, need to be refactored to a type or changed it signature
https://github.com/Praqma/git-phlow/blob/67ae58c4e6ced7eb7c85fd9ab358f159c4d351cc/phlow/workon.go#L17-L81
