### ISSUE TITLE
fix assign and state

### ISSUE THREAD

**Issue by groenborg** [Praqma/git-phlow#232]
The delivered issue #230 added lira and GitHub support, however issues arose with legacy code with broke `assign` and `set label`. 

What needs to be fixed: 

- [x] set label - `GitHub`
- [x] set assignee - `Jira` and `Github`
- [x] set state - `Jira`

**Comment by buep** [comment]
What was the legacy in #230 that blocked you from finish?

**Comment by groenborg** [comment]
@buep I have added link to the legacy code in issue #230 so it is referable in the future :)

**Comment by groenborg** [comment]
I have created mock tests for the new API calls to GitHub and deleted some of the old Convey tests
