### ISSUE TITLE
workon quality feedback

### ISSUE THREAD

**Issue by groenborg** [Praqma/git-phlow#233]
We need to run all tests from the test diagram (in progress) to assure the quality of the workon command and to assert the different possible. 

We will note the failing test cases here in tasks and fix them in this issue

### Fixes

- [x] 1. Cannot resume workspace in JIRA issue 
**Possible Cause** `branchFromIssue` function cannot convert issue ID's with `-` like in Jira `TIS-45`

- [x] 2. Workon when not authorized and no .phlow fails, with and without an issue 
- [x] 3. git phlow auth with wrong url, just says not authorized (needs better message) 
- [x] 4. permprerun only check that you are authorized towards GitHub, which result in a stack trace like issue 2
- [x] 5. Workon fails. I have two git auth options, and specifying -gh as target. It blows up with %A added to my workon.
**Possibel cause*** happens when cloned with https

- [x] 6. Workon with a GitHub issue ID, with a Jira config does not create a branch, but prints assignee and status. Should just fail **CRITICAL**

- [ ] 7. Workon when on a `jira` branch tries to create a new workspace. Should just say that you is already in that workspace

- [x] 8. Phlow spinner messes with formatting on windows

- [ ] 9. git phlow workon with wrong remote, prints and fails. Error should be formatted correctly

**Comment by groenborg** [comment]
2. Stacktrace

panic: 

goroutine 1 [running]:
github.com/praqma/git-phlow/setting.LoadToolSettings(0x13e9e60, 0x0)
	/Users/simon/Go/src/github.com/praqma/git-phlow/setting/setting.go:221 +0x2ed
github.com/praqma/git-phlow/setting.NewToolStg(0x130fa56)
	/Users/simon/Go/src/github.com/praqma/git-phlow/setting/setting.go:67 +0x2d
github.com/praqma/git-phlow/cmd/cmdperm.RequiredAuthentication()
	/Users/simon/Go/src/github.com/praqma/git-phlow/cmd/cmdperm/prerunperm.go:16 +0x26
github.com/praqma/git-phlow/cmd.glob..func18(0x15c7c20, 0x15ebcb8, 0x0, 0x0)
	/Users/simon/Go/src/github.com/praqma/git-phlow/cmd/workon.go:23 +0x25
github.com/spf13/cobra.(*Command).execute(0x15c7c20, 0x15ebcb8, 0x0, 0x0, 0x15c7c20, 0x15ebcb8)
	/Users/simon/Go/src/github.com/spf13/cobra/command.go:643 +0x44b
github.com/spf13/cobra.(*Command).ExecuteC(0x15c75c0, 0xc, 0xc420016990, 0xe)
	/Users/simon/Go/src/github.com/spf13/cobra/command.go:726 +0x2fe
github.com/spf13/cobra.(*Command).Execute(0x15c75c0, 0x0, 0xc420016920)
	/Users/simon/Go/src/github.com/spf13/cobra/command.go:685 +0x2b
github.com/praqma/git-phlow/cmd.Execute()
	/Users/simon/Go/src/github.com/praqma/git-phlow/cmd/root.go:35 +0x31
main.main()
	/Users/simon/Go/src/github.com/praqma/git-phlow/main.go:9 +0x20

**Comment by Sharor** [comment]
PS C:\Users\david\Source\Repos\microservices-meetup> git phlow workon 1 -t gh
Preparing workspace...
An issue with number: 1 could not be found on GitHub
check that it exists or that you have access to it on GitHub
PS C:\Users\david\Source\Repos\microservices-meetup> git phlow workon 1 -t gh -v
Exec: git status
Exec: git config --get phlow.user
Exec: git config --global phlow.token
Exec: git rev-parse --show-toplevel
Preparing workspace...
Exec: git fetch --all
Exec: git branch -a
Exec: git config --get phlow.token
Exec: git config --get phlow.user
Exec: git ls-remote --get-url origin
https://api.github.com/repos/Sharor/microservices-meetup.git%0A/issues/1?access_token=de69b504d1aa0d35a9cf95657fc0f3d4e5
a7fd8d
An issue with number: 1 could not be found on GitHub
check that it exists or that you have access to it on GitHub

**Comment by groenborg** [comment]
9. output

Preparing workspace...

-------- Issue #TIS-69--------  
Issue #TIS-69 could not be moved to 'In Progress'
Assignee => @admin 
fatal: 'simon/master' is not a commit and a branch 'TIS-69-add-a-string-anonymizer-to-textutils' cannot be created from it

**Comment by groenborg** [comment]
This issue have been solved by the referred issues and will be closed
