### ISSUE TITLE
Problems with .phlow

### ISSUE THREAD

**Issue by kryptag** [Praqma/git-phlow#245]
right now if you don't have a `.phlow` file you git-phlow will auto generate a file for you with the default config. This is fine and is actually really nice for users.
```
[default]
remote                 = origin
service                = github
integration_branch     = gh-pages
issue_url              = https://api.github.com
delivery_branch_prefix = ready
```

this is what a auto generated `.phlow` file looks like. Now if i want to add my Jira config i would just change the name from [default] to [jira] and change the other fields to match. If i then run a command that looks at the config file, it will see that i don't have a default section and recreate the file with the default.

Ways to solve this.
1. Don't delete the file and create a new, just tell the user that a [default] section is a must if the user doesn't use the `-target switch`
2. put in a new [default] section in the existing file

**Comment by groenborg** [comment]
This issue is related to #209
