### ISSUE TITLE
Refactor BranchNameConverter

### ISSUE THREAD

**Issue by groenborg** [Praqma/git-phlow#25]
The current converter/filter for creating branch names from GitHub issues needs an overhaul. Regex would maybe help here. 

this could prove helpful: http://stackoverflow.com/questions/3651860/which-characters-are-illegal-within-a-branch-name

**Comment by lakruzz** [comment]
Have a look at https://github.com/Praqma/the-phlow/blob/master/perl/git-phlow#L776
