### ISSUE TITLE
Invalid url generated by `git phlow web`

### ISSUE THREAD

**Issue by nielsoledam** [Praqma/git-phlow#252]
The command `git%25!d(string=1)`returns a broken url:
https://github.com/xxxx/yyyy/issues/%25!d(string=1)

It should have returned:
https://github.com/xxxx/yyyy/issues

phlow specification
sha 		: 731a74c8d4c0451742ef54d8a40f3ad4c94110fa
version 	: 3.1.0
date 	: 11-09-2017

**Comment by groenborg** [comment]
This have been fixed in #247 with a brand new web command that supports several configurations
