### ISSUE TITLE
Review SimpleExec and how system execs are handled

### ISSUE THREAD

**Issue by groenborg** [Praqma/git-phlow#26]
For various reasons, we have chosen to use the local installed Git via Exec calls instead of relying on the git2go (libgit2)library.

This task is about investigating how best to execute commands on a system and handle errors etc.
The current prototype implementation is very simple and might need some improvement.

`git lfs` might be a good example, as they do a bunch of checks and some tty magic. If you have experience with this kind of task in Go, then this is a task for you.

**Comment by lakruzz** [comment]
Not relevant anymore
