### ISSUE TITLE
git-phlow notifies about not moving Jira issue in progress, even though it actually does.

### ISSUE THREAD

**Issue by dangrondahl** [Praqma/git-phlow#269]
It seems that git-phlow doesn't register the state change correctly when moving a Jira issue through `workon`. The Jira issue **is** moved into: "In Progress" :
```
git workon -v PHLOW-6
Exec: git status
Exec: git config --get phlow.service
Exec: git config --get phlow.issue-api
Exec: git config --get phlow.issue-web
Exec: git config --get phlow.remote
Exec: git config --get phlow.delivery-branch-prefix
Exec: git config --get phlow.integration-branch
Preparing workspace...
Exec: git fetch --all
Exec: git branch -a
Exec: git config --get phlow.jirauser
Exec: git config --get phlow.jiratoken

-------- Issue #PHLOW-6--------
Issue #PHLOW-6 could not be moved to 'In Progress'
Assignee => @dgg
Exec: git checkout -b PHLOW-6-this-gets-moved-in-progress origin/master
Created workspace:  PHLOW-6-this-gets-moved-in-progress
```
#### History
![capture](https://user-images.githubusercontent.com/7084600/32072837-5d461442-ba94-11e7-9c7b-586933b6c7ff.png)
#### Jira Workflow
![workflow](https://user-images.githubusercontent.com/7084600/32073009-ef29208e-ba94-11e7-89fc-6f8534899267.png)

**Comment by buep** [comment]
I think we will see if we can write a test to reproduce it, and obviously fix it. It seems to be something around interpreting return code from their API.

**Comment by dangrondahl** [comment]
Fine, let me know if you need more information about our Jira setup.

**Comment by groenborg** [comment]
it could be an api error, we have tested it again 6.x
