### ISSUE TITLE
If I only follow the instructions in README things do not work

### ISSUE THREAD

**Issue by RandomSort** [Praqma/git-phlow#277]
If I follow the readme. After installing the first thing I need to do is to do "git phlow auth" which actually works against GitHub if no configuration has been done.

The issue is then that my next commands will not work because I have not made any configurations. 

Solution is to add description of configuration to README :)

**Comment by RandomSort** [comment]
I'm not sure if this is the same or a separate issue but I get this issue after authenticating.
Both with the default ( ie. no `[phlow]` block besides username and token ), and with explicit configuration copied from the documentation.

![image](https://user-images.githubusercontent.com/582571/32613934-63f6d44c-c56c-11e7-928f-90f5dbbca41b.png)

This happens both in Powershell and Git Bash and cmd. Windows 10. Git phlow installed via chocolatey.

**Comment by RandomSort** [comment]
![image](https://user-images.githubusercontent.com/582571/32614261-2ad2baf4-c56d-11e7-85c7-1a123b1908d3.png)

**Comment by groenborg** [comment]
git phlow has a standard configuration it uses for GitHub. That will be used if no other configuration exists.

**Comment by groenborg** [comment]
If that configuration does not match your setup you need to use it. git bash still does not work.. No terminal emulators work right now

**Comment by buep** [comment]
> No terminal emulators work right now

Strange since we're compliant with such one ;-)

**Comment by RandomSort** [comment]
I'm sorry if I was not explicit enough. This fails with *both* the default configuration and copying explicitly from the documentation to my `.gitconfig`. 
I'm not sure what you mean by that not matching my setup. I was trying to do stuff on the praqma.com repository so I assume that is quite the standard setup :)

**Comment by RandomSort** [comment]
If you need additional information I will be happy to provide this.

**Comment by groenborg** [comment]
it is the ssh:// in front of the GitHub URL which causes this error

**Comment by buep** [comment]
Sorry, but it doesn't make sense to expand and make the regexp more complex... you also forgot to support `file://` .... we need another solution I think.
