### ISSUE TITLE
Pretested integration plugin

### ISSUE THREAD

**Issue by groenborg** [Praqma/git-phlow#28]
This is merely and Idea
The git-phlow project should at some point in time contain functionality to do pretested integration. The commands and functionality, and description of what pretested integration is can be found here: https://github.com/Praqma/concourse/issues/44 

Research or figure out a good way to fit pretested integration into the project. This probably needs some grooming

**Comment by lakruzz** [comment]
Closed with reference to praqma/the-phlow#63
