### ISSUE TITLE
Improve URL handling regexp and add documentation

### ISSUE THREAD

**Issue by buep** [Praqma/git-phlow#280]
This commit https://github.com/Praqma/git-phlow/commit/8d0684d65ec0b48879582d72d7b7a91e13ee3ce2 and issue #277 implement URL handling uses regexp... that is to fragile and I consider it technical debt... isn't there a better way?

We also forgot to support `file://` I guess?

What about also testing `http`?

**Comment by buep** [comment]
@RandomSort do you have a proposal for a more stable solution than regexp handling URL?

Or should we just agree to do an investigation of all possible values to support and say that is good enough?

**Comment by groenborg** [comment]
`http` have been accounted for.. but not `file://` the function itself is not a solution, there should be a better way to extract organization and repo to access githubs API

**Comment by groenborg** [comment]
it is after all a GitHub specific things

**Comment by RandomSort** [comment]
I think we are trying to overthink things. 
At the moment we support two scenarios. EIther no configuration, in which case URLs is already known and can be hardcoded.
Or we can have a configuration to something else ( or to github.com, but with explicit configuration that doesn't matter ). This means we should never actually have to parse the url.

We might have tried to over generalize something :)

If we want to split out into multiple different things we could split it into a "backend" class that contains a base url or something. In most cases I'd assume that we'd be able to infer some of this configuration but that is probably for further scenarios.

So solution is basically not to extend this, but to remove this logic :D

**Comment by buep** [comment]
We have been diving into this... here is more explanation.

If I run `git phlow config show` in my repository the configuration could look like this:

```
Service: github
IntegrationBranch: master
Remote: origin
IssueApi: https://api.github.com
IssueWeb: https://github.com
PipelineUrl: none
DeliveryBranchPrefix: ready
Scope: internal
INIBlock: 
```

This configuration snippet is generic for also jira, in the sense it have the same keys. We're only talking about the url used for task management part of git-phlow.

The github api requires an organization and repository name is queries, e.g. `https://api.github.com/repos/Praqma/git-phlow`.

Today these are passed from the git remote url. Hence the code we're discussing.

For Jira, we don't need those two values, as all API requests are on the same url and not related to any project, organization or repository, but the Jira base url itself.

So this means if we should not add two extra configuration keys (org + repo) for the git phlow configuration when using _only_ github and not jira, we need to get them from somewhere.
And the Github API doesn't support asking for those based on an URL, which would have been nice.

So @RandomSort now I also believe we have to do something to get the url. We can use it directly, as 

`https://github.com/Praqma/git-phlow/` somehow have to be translated to for example `https://api.github.com/repos/Praqma/git-phlow` or `git@github.com:Praqma/git-phlow.git` translated to `https://api.github.com/repos/Praqma/git-phlow`.

We could introduce a drift in configuration between jira and github, and add two keys more to the github organization called `org` and `repo` so we only have to parse it once.
We could even implement a command where we could generate a configuration interactively with the user to confirm or edit it.
But we wouldn't have the same two keys for jira.


I recommend to close this issue, and not introduce a different configuration for jira vs github.

**Comment by RandomSort** [comment]
That makes sense.
Assumption could then be that remote is of format: /(?.*)\/(.*)\/(.*)(?:\.git)/ which will then give project in $1 and repo in $2 doesn't care about anything other than the last two // :D

**Comment by buep** [comment]
Yes, @groenborg would it make sense to simplify the regexp as a commit on this case before closing?

Also I would like a few lines of documentation on our above arguments why it is needed so we have that piece of decision making with the actual code.

**Comment by groenborg** [comment]
I will not correct the regex for appearance sake. I will however add some documentation to the function, so you guys know what is going on.
