### ISSUE TITLE
Describe a containerized development environment

### ISSUE THREAD

**Issue by groenborg** [Praqma/git-phlow#29]
Get a go development environment up and running In a docker container, and make it available

**Comment by buep** [comment]
I'm done doing apt-get install.... I need a container.

**Comment by buep** [comment]
mkdir -p golangdevelopment/src/github.com/praqma
cd golangdevelopment/src/github.com/praqma
git clone git@github.com:Praqma/git-phlow.git
cd ../../../

docker run --rm -v $PWD:/go -w /go/src/github.com/praqma/git-phlow golang:1.6 go get
docker run --rm -v $PWD:/go -w /go/src/github.com/praqma/git-phlow golang:1.6 go build -v

Ugly... since I either have to set the -w (docker working dir) or the current directory to mount into go.

**Comment by buep** [comment]
Kind of also ugly the way we build currently with go in concourse: https://github.com/Praqma/git-phlow/blob/1a3e44a8eeebf677f8ea783f91889789317f9885/ci/tasks/test.sh

We have to move the cloned repository, then we have to manually fetch every dependency, this means when I add another dependency, I do not only need to add it to the project, but also remember to add it to the build script.

**Comment by buep** [comment]
It seems to be all based on this repository structure... where Golang is all in one folder, while each project is a sub-path of that.
http://stackoverflow.com/a/14870666

**Comment by buep** [comment]
So I would say my issue now is how to build completely isolated, from within the repository root of a git project with go package.
Or if not - why I don't want that.

**Comment by buep** [comment]
https://golang.org/doc/code.html#Organization

**Comment by buep** [comment]
original idea is not to have to install go to run `go build -v`

then run `docker run --rm mygobuildenv:1.6 build -v` for example. Maybe even alias it with `go` ...

**Comment by buep** [comment]
Taking out of progress... I'll continue on next code café ...

**Comment by groenborg** [comment]
We are gonna have the Code Cafe the 7th, is it possible to finish this before that so people can use your findings at the Code Cafe

**Comment by buep** [comment]
I don't have time... but I think it should be a must have issue.

Maybe something plex can do during next week?

**Comment by groenborg** [comment]
not everyone use containers as toolboxes in their workflow so having it as a must have may be overrating it. However I think it would be nice for maintainers in the future to just spin up a docker container removing the whole setup step, so it should take some priority

**Comment by buep** [comment]
@drBosse - you have a go container?

**Comment by buep** [comment]
This is a step in the right direction... but if I savage the pieces from this repository I find relevant I'm still back to the old problem with the dependencies.

https://github.com/thockin/go-build-template

I'm wondering if we're doing our dependency management properly? @groenborg - which best-practice did you base your repository layout on and the way we download dependencies with git?

**Comment by buep** [comment]
I think the solution is a combination of the Makefile from the above repository and the things in your CI build included in https://github.com/Praqma/git-phlow/blob/master/ci/scripts/build.sh

**Comment by buep** [comment]
I'll write a new issues that is more clear and that describe the use-case better. Then close this.

**Comment by buep** [comment]
Closing, see #130 on better ideas for continuing.
