### ISSUE TITLE
Andreas needs contributor status

### ISSUE THREAD

**Issue by lakruzz** [Praqma/git-phlow#313]
@JKrag @groenborg @MichaelMadsen @praqma-thi 

Hi Friends.

We need to fix som broken stuff in this repo.

Can you please add @ansty93 to the list of contributors ...ASAP :-)

Thanks

@Lakruzz

**Comment by JKrag** [comment]
@lakruzz I have added Andreas, but it would have been nice with a bit more explanation that "some broken stuff". :-)

**Comment by astyltsvig** [comment]
Hello @JKrag  - Thank you for adding me!
Yes definitely, i will soon come with some descriptions of issues with git-phlow ;)

**Comment by astyltsvig** [comment]
Hereby closing the issue.
