### ISSUE TITLE
Add the ability to run a test during deliver

### ISSUE THREAD

**Issue by lakruzz** [Praqma/git-phlow#54]
As described in praqma/the-phlow#63

**Comment by JKrag** [comment]
In other words, we want git phlow deliver to support the following syntax:

`git phlow deliver --local --test <testscript>`

where the actual deliver part is only done if `testscript` return with exit code zero.
Functionally this should be equivalent with:

`testscript && git phlow deliver --local` 

in shells that support this syntax. We are just making it more user friendly.

**Comment by lakruzz** [comment]
Related to #53
