### ISSUE TITLE
Create package for Brew

### ISSUE THREAD

**Issue by lakruzz** [Praqma/git-phlow#56]

**Comment by groenborg** [comment]
http://stackoverflow.com/questions/33112491/homebrew-whom-to-ask-for-a-formula-to-be-added

**Comment by groenborg** [comment]
The right way to release binaries is with brew bottles, but the normal installation works perfectly fine, but if we link the repository instead we can build locally

class GitPhlow < Formula
  desc "pragmatic workflow extension for git"
  homepage "https://github.com/Praqma/git-phlow"
  url "https://github.com/Praqma/git-phlow/releases/download/v0.1.5/git-phlow-0.1.5-darwin-amd64.tar.gz"
  version "0.1.5"
  sha256 "2f3eeafb0a0c83e93eedd420679de09d0380a30b8a5f7e21be5a1d471e1fc54f"

  bottle do
      cellar :any_skip_relocation
      sha256 "a4a8805b18f1f5b60e027cbfb2a4593511d6cda2f86d9a66d9509e63651748c9" => :sierra
  end

  def install
    bin.install "git-phlow"
  end
  test do
    system "true"
  end
end
