### ISSUE TITLE
`git phlow workon`/ `git-phlow workon`  is not finding remote issues 

### ISSUE THREAD

**Issue by Robertelving** [Praqma/git-phlow#64]
**Steps to reproduce**
1. Installation through wget command in README.
2. Authenticated github through `git phlow auth` 
3. `git phlow workon 18` returns 

![image](https://cloud.githubusercontent.com/assets/6860058/23997740/ed458f84-0a52-11e7-824e-cd2d453ac0e6.png)

Checked that Issues are there using ghi:
![image](https://cloud.githubusercontent.com/assets/6860058/23997798/2f50dff0-0a53-11e7-95f7-963f0279abdd.png)

**Comment by groenborg** [comment]
Thanks for submitting the bug. We will get right at it

**Comment by ChristopherMortensen** [comment]
Note, this has been performed on a repo located in an organization.

**Comment by groenborg** [comment]
The bug have been located.
The current version of extracting the organization and user assumes the repo have been cloned using ssh and not http.

**Comment by groenborg** [comment]
the issue have been fixed and the changes will make it into production in the next release
