### ISSUE TITLE
No local issue-branches found

### ISSUE THREAD

**Issue by meekrosoft** [Praqma/git-phlow#68]
This on the praqma.com repo...

```
git phlow workon 640
Fetching changes from remote
Locating existing issue branches
No local issue-branches found. Searching github

No issues matches you input
```

```
 ~/tmp/praqma/praqma.com>   gh-pages  ghi list 640 | grep 640
  640  Get rid of the "and DevOps"  [Prio 2 - should have] [Status - up Next] 1
```

**Comment by groenborg** [comment]
@meekrosoft this issue is related to #64 and have been fixed now.. I will release the fix as soon as possible

**Comment by groenborg** [comment]
If the issue persists in version 1.0.6 further information will be needed, can you please do following things. 
1. Submit the verbose output of the workon command
2. Is the repository a fork of another project? 
3. provide upstream and remote url

Thanks for you feedback

**Comment by meekrosoft** [comment]
Version: `praqma/praqma-tap/git-phlow 1.0.6`

Output:
```
git phlow -v workon 640
git status
Fetching changes from remote
git fetch --all
git rev-parse --abbrev-ref HEAD
git branch -a
Locating existing issue branches
No local issue-branches found. Searching github
git config branch.master.remote

git config branch.master.remote
git config branch..remote
No issues matches you input
```

Remotes:
```
git remote -v
origin	git@github.com:Praqma/praqma.com.git (fetch)
origin	git@github.com:Praqma/praqma.com.git (push)
```

**Comment by groenborg** [comment]
from the output it seems that the changes I made from issue #64 did not make it into this binary! I have added a verbose output which should help trouble shooting. It will be released within a short period of time. Hopefully the issue will not be relevant by that
