### ISSUE TITLE
404 when listing issues

### ISSUE THREAD

**Issue by lakruzz** [Praqma/git-phlow#71]
Although genuinely impressed by the install procedure :+1:

My fist choice of command (following `mkalias`) was `issue` which didn't pan out too well:

![image](https://cloud.githubusercontent.com/assets/155492/24156371/a599d9d0-0e56-11e7-99dc-314d65c4266d.png)

**Comment by lakruzz** [comment]
It's actually not the URL that's the problem - it's the authentication:

This one works fine:
```
curl -s -i -u :c3832d7afxxxxxxxxxxxxxxxxa8823dc21d9b8f6 https://api.github.com/repos/Praqma/praqma.com/issues
```


but 
```
curl -s -i https://api.github.com/repos/Praqma/praqma.com/issues
```

Dies:
![image](https://cloud.githubusercontent.com/assets/155492/24156555/28824e54-0e57-11e7-8819-7fd1c8c8a1b8.png)

**Comment by lakruzz** [comment]
I expected that `git auth` would be my rescue

But:

![image](https://cloud.githubusercontent.com/assets/155492/24156737/b39a2890-0e57-11e7-8a93-84ddea444458.png)

**Comment by lakruzz** [comment]
Hmmm

The token was generated and added to my `.gitconfig` file:

```
[phlow]
	token = 028b751455a11beb4feea4bf104f0ce0658af21c
	user = lakruzz
```

but still it seems invalid:

![image](https://cloud.githubusercontent.com/assets/155492/24156891/25f8950c-0e58-11e7-9d22-a42e623d0553.png)

**Comment by lakruzz** [comment]
It looks like I haven't been given sufficient access:

![image](https://cloud.githubusercontent.com/assets/155492/24156995/7c042682-0e58-11e7-843a-6eeded92dddf.png)

I have this:

![image](https://cloud.githubusercontent.com/assets/155492/24157065/9e18e7f8-0e58-11e7-83e6-5b569be0b93b.png)

When I change to:

![image](https://cloud.githubusercontent.com/assets/155492/24157141/d307c8bc-0e58-11e7-8a86-45d4dabaa0c7.png)

....

```
curl -s -i -u :028b751455a11beb4feea4bf104f0ce0658af21c https://api.github.com/repos/Praqma/praqma.com/issues
``` 

actually works

**Comment by lakruzz** [comment]
....AAArgh

```
git issues 
```

still fails

**Comment by lakruzz** [comment]
It works on public repos, but not private:

![image](https://cloud.githubusercontent.com/assets/155492/24167830/8a071fa8-0e78-11e7-8705-b0e51694c776.png)

**Comment by groenborg** [comment]
yes the phlow only works with public repos, but I will look and the access rights and so it works with private repos too. 
Thanks for the feedback
