### ISSUE TITLE
Err when establishing build environment

### ISSUE THREAD

**Issue by lakruzz** [Praqma/git-phlow#73]
Following the nice CONTRIBUTING instructions I did

``` shell
brew unlink go # Uninstall old version
brew install golang
mkdir $HOME/go-projects
atom ~/.zshrc - #adding the GO settings - see below
go get -v github.com/praqma/git-phlow
cd $GOPATH
cd src/github.com/praqma/git-phlow
go get -d -t -v ./...
go build
```

My `.zshrc`contains

``` shell
export GOPATH=$HOME/go-projects
export GOBIN=/usr/local/opt/go/libexec/bin
export PATH=$PATH:$GOBIN
```

At this point my `go build` fails due to a plugin error:

![image](https://cloud.githubusercontent.com/assets/155492/24187947/a79887fc-0edf-11e7-8f33-fb5d6f68ffe4.png)

**Comment by lakruzz** [comment]
And it's actually true!
Looking at my dependency:

```shell
cat $GOBIN/../src/net/http/status.go | grep "StatusUnprocessableEntity"   
```

I get absolutely nothing . while for instance [`StatusOK`](https://github.com/Praqma/git-phlow/blob/master/plugins/github.go#L297) works like a charm:

![image](https://cloud.githubusercontent.com/assets/155492/24189955/49dd4b86-0ee7-11e7-975f-392d176bbc75.png)

Something is fishy!

**Comment by groenborg** [comment]
@lakruzz That is very funny indeed. but I might know what the problem is. I think it's the go version

**Comment by lakruzz** [comment]
Hmmm - That' (5818507) more of a work around isn't it!

It's _supposed_ to be valid: https://golang.org/src/net/http/status.go

``` shell 
>go version
go version go1.6 darwin/amd64
```

**Comment by lakruzz** [comment]
My build works no - with your fix, but maybe we should keep this one open for the backlog and a permanent fix?
