### ISSUE TITLE
Suggestion: 'checkout master' after 'git phlow deliver'

### ISSUE THREAD

**Issue by ChristopherMortensen** [Praqma/git-phlow#75]
Just a minor suggestion to ease up the work flow.
Since git phlow closes the issue it could be a nice feature to let it checkout the master branch afterwards. 

Thumbs up for a nice tool!

**Comment by groenborg** [comment]
I think that is a good suggestion. I will make it default behaviour
Thanks for the feedback

**Comment by buep** [comment]
Related to #264
