### ISSUE TITLE
os.hostname() fails on Linux subsystem for windows

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/git-phlow#77]
open /proc/sys/kernel/hostname: no such file or directory

**Comment by groenborg** [comment]
To make it compliant with windows we need to remove the os.hostname function and find another solution.
https://github.com/Praqma/git-phlow/blob/master/plugins/gh.go#L143

**Comment by MadsNielsen** [comment]
I'm closing this. We should not attempt to bandaid a solution if we can do a native windows binary. 

See #129
