### ISSUE TITLE
Suggestion: Remove 'In Progress tag when delivering'

### ISSUE THREAD

**Issue by Robertelving** [Praqma/git-phlow#80]
This is mostly for Waffle Purposes. Currently ending with a lot of Tasks/Issues in done collumn with 'In Progress' on.

![image](https://cloud.githubusercontent.com/assets/6860058/24247728/16c27bb8-0fcd-11e7-85f0-654abb13b2cf.png)

**Comment by groenborg** [comment]
This is not a phlow issue. If waffle is configured correctly, labels determining columns will not be shown. Also as long as work is finished with `wrapup` the message will close the issue and the issue will no longer be present on the backlog or issue log. If you have questions on how to set this up, feel free to write. 

I am closing this issue
