### ISSUE TITLE
Add fail for missing main branch

### ISSUE THREAD

**Issue by lakruzz** [Praqma/git-phlow#86]
I have a situation where an internally executed command fails, it should have caused an error!

![image](https://cloud.githubusercontent.com/assets/155492/25389720/a91d49f2-29d1-11e7-824c-c4093fec30fe.png)

```shell
git config branch..remote
```

**Comment by groenborg** [comment]
thanks for the issue submit, I will address the issue

**Comment by groenborg** [comment]
This is possibly related to issue #87 The token is not authorized but does not fail and therefore the main branch can not be located! I will rename this issue and aim it to address the problem if we can not locate the main branch from GitHub e.g. prompt the user for the name

**Comment by groenborg** [comment]
This issues will be fixed when #87 is fixed, but I think a fail is still in place e.g. if there is no default branch.

**Comment by groenborg** [comment]
with the new .gitconfig setup this issue is no longer relevant
