### ISSUE TITLE
return wrap-up to default behavior

### ISSUE THREAD

**Issue by lakruzz** [Praqma/git-phlow#89]
![image](https://cloud.githubusercontent.com/assets/155492/25392382/ccde5906-29d8-11e7-8d97-281c3612297b.png)

It says that it add all the work from the working area, but you actually have to run `git add`your self!

**Comment by groenborg** [comment]
in relation to a discussion about wrapup, I removed the default behaviour of adding everything when the command is called. wrapup --hard will auto add

**Comment by groenborg** [comment]
Wrapup will be changed to the previous default behavior where it automatically adds all changes. Hard will be removed, and a "skip-add" added in stead.
