### ISSUE TITLE
Prettify output of deliver --local

### ISSUE THREAD

**Issue by lakruzz** [Praqma/git-phlow#92]
![image](https://cloud.githubusercontent.com/assets/155492/25431068/51e23fd6-2a7f-11e7-8204-c4a6c3f349d6.png)

Don't have to be this verbose - unless I've used `--verbose``

"trying to..." sounds like we're not sure if we will succeed

The text reads:

```
Merging changes from branch 1-add-welcome-slide-deck into branch master 
Pushing changes to remote master 
Changes from 1-add-welcome-slide-deck delivered to master 
```

But most of it is printed in black  - so it's really hard to read :-(

**Comment by groenborg** [comment]
There seems to be issues with the Color sequences. The output will be formatted
