### ISSUE TITLE
Typo in 'workon' output

### ISSUE THREAD

**Issue by praqma-thi** [Praqma/git-phlow#93]
When calling `git phlow workon #`, there's a typo in the progress message that appears.
The spinner displays "Fetching form remote", this should be "Fetching from remote".

Relevant file:
https://github.com/Praqma/git-phlow/blob/e8525bce7773ec6559be15a4c9d4714e14c12c64/phlow/workon.go

**Comment by RandomSort** [comment]
I might have opened a duplcate issue #95 that I accidentially pushed a fix to.

**Comment by groenborg** [comment]
I am closing the issue since it has been solved in #95 as @RandomSort said.
