### ISSUE TITLE
MoM - 6th Gathering

### ISSUE THREAD

**Issue by JKrag** [Praqma/git-phlow#98]
MoM scribed by @lakruzz 

## Participants
Kamstrup, Volvo, MAN D&T

## A small recap.

What choices have been made implicitly in the tool, what if we have long lived branches.

Support for different branching strategies - especially long-lived feature branches and release branches.

When we are at a brink of a release - and need to go on to the next. We need a temporary stabilization branch. as in the git-flow.

We explain how resuming work on a branch using workon implicitly makes a pull --rebase

This should be configurable.

Talking about declarative pipelines.

Windows support is required.

Dan is suggesting that `workon` should take a parameter too - we seem to agree that the current implementation is better.

What happens if you forget to wrapupand do workon+ deliver

We're talking about Atlassian integration.

Jira+Bitbucket

Jira+GitHub

Volvo hasn't decided yet if they go with one on the other.

Jira is already integration with Bitbucket - so maybe it's really just a Jira integration.

How do we handle pull requests? It's required

Multiple long-lived/integration branch support is required (Samuel)

Task creating form the command line? is it relevant? Needed?

The Command line focus is kinda cool, and might help people actually use the command line better.

We're discussing - park/share - it's needed.

**Comment by JKrag** [comment]
We created some post-its with ideas during the workshop. We only half-finished prioritisation of these.
Based on that work and my judgement call on what I heard during the rest of the workshop, my best summary would be the following:

## M (Must have):

- JIRA support for issues (Kamstrup, volvo, MAN?)
- Windows support (MAN - must have!)
- Configurable target branch


## S (should have): 
- Park/share feature
- Command:  (status?) show what I have:
	- which branches in progress
	- what unfinished work
	- what is waiting in queue?
- Investigate best support for good branching strategy/workflow during stabilisation phase
- Investigate best support for multiple long lived branches

## C (could have):
- Create new issues from `git phlow`
- Investigate if there is special needs when working with hierarchical issue types in e.g. JIRA

**Comment by groenborg** [comment]
The statements of work have been completed and the gathering is over so I will close this issue
